### ISSUE TITLE
Breaked DB order

### ISSUE THREAD

**Issue by JJQuest** [uglide/RedisDesktopManager#3443]
After RDM start, i see crazy db sort order.

![screenshot from 2015-08-19 10 19 18](https://cloud.githubusercontent.com/assets/13865255/9350802/5831acb8-465c-11e5-9452-50698c17afb8.png)

Then click on db9, RDM draw triangle on db4, and don't open db9.
If  click 5+ more time on db9, RDM make magic, and open db9.

![screenshot from 2015-08-19 10 21 44](https://cloud.githubusercontent.com/assets/13865255/9350825/94af8b10-465c-11e5-993f-6f524dc199c1.png)

If click on db0 - db3 it's work normal

Mint 17.2 clean install Redis 3.0.2

**Comment by uglide** [comment]
Fixed in 0.8.0-RC4
