### ISSUE TITLE
Build from source errors

### ISSUE THREAD

**Issue by janekdb** [uglide/RedisDesktopManager#3638]
RDM Version: Current
Environment (OS name and version): Ubuntu Trusty
Redis Server Version:

Steps to reproduce:

1. Follow instuctions here http://docs.redisdesktop.com/en/latest/install/#build-from-source

2. Build fails on this line,

```
source /opt/qt54/bin/qt55-env.sh && make && sudo make install
```

`qt55-env.sh` does not exists so I change it to `qt54-env.sh`

```
cd src/
./configure
source /opt/qt54/bin/qt54-env.sh && make && sudo make install
cd /usr/share/redis-desktop-manager/bin
mv qt.conf qt.backup
```

3. Run the commands again resulting in this error,

```
====================================================================
Run: source /opt/qt54/bin/qt54-env.sh && qmake && make
====================================================================
make: *** No targets specified and no makefile found. Stop.
build.sh: line 4: cd: /usr/share/redis-desktop-manager/bin: No such file or directory
mv: cannot stat ‘qt.conf’: No such file or directory
```

Expected result: rdm binary

Actual Result: build error

**Comment by uglide** [comment]
@janekdb I do not provide any help with building RDM from source anymore. You will be able to download ready-to-use deb's for ubuntu with paid subscription from redisdesktop.com. More info here https://redisdesktop.com/subscribe

**Comment by TheComputerGenie** [comment]
> I do not provide any help with building RDM from source anymore....with paid subscription...

Translation:
Pay me and I'll help you fix the setup I botched.

**Comment by mhohai** [comment]
Ubuntu 16.04 build
```
sudo apt-get install qt5-qmake qtdeclarative5-dev libssh2-1-dev  # checkinstall
```
change `source /opt/qt55/bin/qt55-env.sh`  -> `qmake`

please support uglide and support open source.
[deb](http://45.78.38.197/ss/rdm_0.8.7-1_amd64.deb)  but my deb is so small, it's make by checkinstall

**Comment by mhohai** [comment]
![new...](http://img.vim-cn.com/09/c667d383de241aaecf2a8d8d02a817ba51202c.png)

**Comment by raitucarp** [comment]
@uglide 

> I do not provide any help with building RDM from source anymore. You will be able to download ready-to-use deb's for ubuntu with paid subscription from redisdesktop.com. More info here https://redisdesktop.com/subscribe

That's fair enough. 

However, you may need to consider delete these:
![rdm-build-from-source](https://cloud.githubusercontent.com/assets/163585/18225303/d8331dfe-7219-11e6-8e2a-59906ee7f14d.png)

and

![rdm-build-from-source2](https://cloud.githubusercontent.com/assets/163585/18225302/d7d55048-7219-11e6-91aa-a73db4ccf603.png)

Don't make promise to users.

**Comment by uglide** [comment]
@raitucarp train your linux skills, or consider to buy Windows for free stuff

**Comment by raitucarp** [comment]
> train your linux skills, or consider to buy Windows for free stuff

:+1:  Red herring at its best

**Comment by Stafox** [comment]
I build from sources the latest stable version `0.8.8`.
But got an issue:
White area instead of data viewer.

![rdm-1](https://cloud.githubusercontent.com/assets/1101646/22330431/3d8edf92-e3d7-11e6-90ca-396a9a9716b1.png)
![rdm-2](https://cloud.githubusercontent.com/assets/1101646/22330436/42986058-e3d7-11e6-8798-ddc603f163b7.png)

@uglide Do you know what is the issue?

If I run from terminal, there is no errors: only this (on click on key):

```
Run command: "type 5bdaa1e3-dfe1-11e6-9355-742f68d9689e"  in db  13  with timeout  60000
Bytes written to socket 57
Run command: "ttl 5bdaa1e3-dfe1-11e6-9355-742f68d9689e"  in db  13  with timeout  60000
Bytes written to socket 56
Run command: "LLEN 5bdaa1e3-dfe1-11e6-9355-742f68d9689e"  in db  13  with timeout  60000
Bytes written to socket 57
GoogleMP showScreen  "ValueEditor-list"
GoogleMP networkreply: QVariant(int, 200)
```

**Comment by tagama** [comment]
https://hub.docker.com/r/benoitg/redis-desktop-manager/

**Comment by ssjunior** [comment]
@raitucarp @uglide Looks like the best thing to do is to remove instructions that does not work and do not give any false directions to avoid people loosing their times...

**Comment by con5cience** [comment]
I also had problems compiling Redis Desktop Manager (on Fedora), and thanks to the attitude displayed by the developer in this GitHub issue I have decided to completely abandon any attempt to use the product and installed http://fastoredis.com/ instead -- which had RPMs and other native packages available for download, and worked flawlessly out of the box.

**Comment by uglide** [comment]
@con5cience good FastoRedis promotion, but Medis is much better alternative :)

**Comment by topilski** [comment]
Hi @uglide your answers are very rude, I'm very disappointed of you. 
Hi @con5cience, thank you for feedback.

**Comment by uglide** [comment]
I was rude - it's true. But it because I really hate idle talks like this. Open source is about participating and contributing and not about consuming and blaming.
